# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fitplane/PlaneMap.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fitplane.msg

class PlaneMap(genpy.Message):
  _md5sum = "0eee82ac8b4aa09e68a738e9785183cb"
  _type = "fitplane/PlaneMap"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 width
int16 height
float32 resolution
float32 origin_x
float32 origin_y
Plane[] PlaneGridMap
================================================================================
MSG: fitplane/Plane
float32 PlaneCellHeight
float32 PlaneCellAngle
"""
  __slots__ = ['width','height','resolution','origin_x','origin_y','PlaneGridMap']
  _slot_types = ['int16','int16','float32','float32','float32','fitplane/Plane[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       width,height,resolution,origin_x,origin_y,PlaneGridMap

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlaneMap, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.width is None:
        self.width = 0
      if self.height is None:
        self.height = 0
      if self.resolution is None:
        self.resolution = 0.
      if self.origin_x is None:
        self.origin_x = 0.
      if self.origin_y is None:
        self.origin_y = 0.
      if self.PlaneGridMap is None:
        self.PlaneGridMap = []
    else:
      self.width = 0
      self.height = 0
      self.resolution = 0.
      self.origin_x = 0.
      self.origin_y = 0.
      self.PlaneGridMap = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2h3f().pack(_x.width, _x.height, _x.resolution, _x.origin_x, _x.origin_y))
      length = len(self.PlaneGridMap)
      buff.write(_struct_I.pack(length))
      for val1 in self.PlaneGridMap:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.PlaneCellHeight, _x.PlaneCellAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.PlaneGridMap is None:
        self.PlaneGridMap = None
      end = 0
      _x = self
      start = end
      end += 16
      (_x.width, _x.height, _x.resolution, _x.origin_x, _x.origin_y,) = _get_struct_2h3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.PlaneGridMap = []
      for i in range(0, length):
        val1 = fitplane.msg.Plane()
        _x = val1
        start = end
        end += 8
        (_x.PlaneCellHeight, _x.PlaneCellAngle,) = _get_struct_2f().unpack(str[start:end])
        self.PlaneGridMap.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2h3f().pack(_x.width, _x.height, _x.resolution, _x.origin_x, _x.origin_y))
      length = len(self.PlaneGridMap)
      buff.write(_struct_I.pack(length))
      for val1 in self.PlaneGridMap:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.PlaneCellHeight, _x.PlaneCellAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.PlaneGridMap is None:
        self.PlaneGridMap = None
      end = 0
      _x = self
      start = end
      end += 16
      (_x.width, _x.height, _x.resolution, _x.origin_x, _x.origin_y,) = _get_struct_2h3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.PlaneGridMap = []
      for i in range(0, length):
        val1 = fitplane.msg.Plane()
        _x = val1
        start = end
        end += 8
        (_x.PlaneCellHeight, _x.PlaneCellAngle,) = _get_struct_2f().unpack(str[start:end])
        self.PlaneGridMap.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_2h3f = None
def _get_struct_2h3f():
    global _struct_2h3f
    if _struct_2h3f is None:
        _struct_2h3f = struct.Struct("<2h3f")
    return _struct_2h3f
