// Generated by gencpp from file fitplane/GridPlaneInfo.msg
// DO NOT EDIT!


#ifndef FITPLANE_MESSAGE_GRIDPLANEINFO_H
#define FITPLANE_MESSAGE_GRIDPLANEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace fitplane
{
template <class ContainerAllocator>
struct GridPlaneInfo_
{
  typedef GridPlaneInfo_<ContainerAllocator> Type;

  GridPlaneInfo_()
    : header()
    , resolution(0.0)
    , width(0)
    , height(0)
    , origin()
    , traversability()
    , plane_angle()
    , plane_height()
    , occupancy()  {
    }
  GridPlaneInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , width(0)
    , height(0)
    , origin(_alloc)
    , traversability(_alloc)
    , plane_angle(_alloc)
    , plane_height(_alloc)
    , occupancy(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _traversability_type;
  _traversability_type traversability;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _plane_angle_type;
  _plane_angle_type plane_angle;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _plane_height_type;
  _plane_height_type plane_height;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _occupancy_type;
  _occupancy_type occupancy;





  typedef boost::shared_ptr< ::fitplane::GridPlaneInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fitplane::GridPlaneInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GridPlaneInfo_

typedef ::fitplane::GridPlaneInfo_<std::allocator<void> > GridPlaneInfo;

typedef boost::shared_ptr< ::fitplane::GridPlaneInfo > GridPlaneInfoPtr;
typedef boost::shared_ptr< ::fitplane::GridPlaneInfo const> GridPlaneInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fitplane::GridPlaneInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fitplane::GridPlaneInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fitplane::GridPlaneInfo_<ContainerAllocator1> & lhs, const ::fitplane::GridPlaneInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.resolution == rhs.resolution &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.origin == rhs.origin &&
    lhs.traversability == rhs.traversability &&
    lhs.plane_angle == rhs.plane_angle &&
    lhs.plane_height == rhs.plane_height &&
    lhs.occupancy == rhs.occupancy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fitplane::GridPlaneInfo_<ContainerAllocator1> & lhs, const ::fitplane::GridPlaneInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fitplane

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fitplane::GridPlaneInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane::GridPlaneInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane::GridPlaneInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16e811bb180035be79c09c3399b1506a";
  }

  static const char* value(const ::fitplane::GridPlaneInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16e811bb180035beULL;
  static const uint64_t static_value2 = 0x79c09c3399b1506aULL;
};

template<class ContainerAllocator>
struct DataType< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fitplane/GridPlaneInfo";
  }

  static const char* value(const ::fitplane::GridPlaneInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 resolution\n"
"uint32 width\n"
"uint32 height\n"
"geometry_msgs/Point origin\n"
"float32[] traversability  # 每个栅格的可通行性\n"
"float32[] plane_angle    # 每个栅格的平面角度\n"
"float32[] plane_height   # 每个栅格的高度\n"
"int32[] occupancy       # 栅格占用状态：-1未知，0空闲，100占用 \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::fitplane::GridPlaneInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.origin);
      stream.next(m.traversability);
      stream.next(m.plane_angle);
      stream.next(m.plane_height);
      stream.next(m.occupancy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridPlaneInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fitplane::GridPlaneInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fitplane::GridPlaneInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "traversability: ";
    if (v.traversability.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.traversability.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.traversability[i]);
    }
    if (v.traversability.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plane_angle: ";
    if (v.plane_angle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.plane_angle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.plane_angle[i]);
    }
    if (v.plane_angle.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plane_height: ";
    if (v.plane_height.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.plane_height.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.plane_height[i]);
    }
    if (v.plane_height.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "occupancy: ";
    if (v.occupancy.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.occupancy.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.occupancy[i]);
    }
    if (v.occupancy.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // FITPLANE_MESSAGE_GRIDPLANEINFO_H
