// Generated by gencpp from file fitplane/PlaneMap.msg
// DO NOT EDIT!


#ifndef FITPLANE_MESSAGE_PLANEMAP_H
#define FITPLANE_MESSAGE_PLANEMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fitplane/Plane.h>

namespace fitplane
{
template <class ContainerAllocator>
struct PlaneMap_
{
  typedef PlaneMap_<ContainerAllocator> Type;

  PlaneMap_()
    : width(0)
    , height(0)
    , resolution(0.0)
    , origin_x(0.0)
    , origin_y(0.0)
    , PlaneGridMap()  {
    }
  PlaneMap_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)
    , resolution(0.0)
    , origin_x(0.0)
    , origin_y(0.0)
    , PlaneGridMap(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _width_type;
  _width_type width;

   typedef int16_t _height_type;
  _height_type height;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef float _origin_x_type;
  _origin_x_type origin_x;

   typedef float _origin_y_type;
  _origin_y_type origin_y;

   typedef std::vector< ::fitplane::Plane_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fitplane::Plane_<ContainerAllocator> >> _PlaneGridMap_type;
  _PlaneGridMap_type PlaneGridMap;





  typedef boost::shared_ptr< ::fitplane::PlaneMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fitplane::PlaneMap_<ContainerAllocator> const> ConstPtr;

}; // struct PlaneMap_

typedef ::fitplane::PlaneMap_<std::allocator<void> > PlaneMap;

typedef boost::shared_ptr< ::fitplane::PlaneMap > PlaneMapPtr;
typedef boost::shared_ptr< ::fitplane::PlaneMap const> PlaneMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fitplane::PlaneMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fitplane::PlaneMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fitplane::PlaneMap_<ContainerAllocator1> & lhs, const ::fitplane::PlaneMap_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.resolution == rhs.resolution &&
    lhs.origin_x == rhs.origin_x &&
    lhs.origin_y == rhs.origin_y &&
    lhs.PlaneGridMap == rhs.PlaneGridMap;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fitplane::PlaneMap_<ContainerAllocator1> & lhs, const ::fitplane::PlaneMap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fitplane

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fitplane::PlaneMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fitplane::PlaneMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane::PlaneMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane::PlaneMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane::PlaneMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane::PlaneMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fitplane::PlaneMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0eee82ac8b4aa09e68a738e9785183cb";
  }

  static const char* value(const ::fitplane::PlaneMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0eee82ac8b4aa09eULL;
  static const uint64_t static_value2 = 0x68a738e9785183cbULL;
};

template<class ContainerAllocator>
struct DataType< ::fitplane::PlaneMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fitplane/PlaneMap";
  }

  static const char* value(const ::fitplane::PlaneMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fitplane::PlaneMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 width\n"
"int16 height\n"
"float32 resolution\n"
"float32 origin_x\n"
"float32 origin_y\n"
"Plane[] PlaneGridMap\n"
"================================================================================\n"
"MSG: fitplane/Plane\n"
"float32 PlaneCellHeight\n"
"float32 PlaneCellAngle\n"
;
  }

  static const char* value(const ::fitplane::PlaneMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fitplane::PlaneMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.resolution);
      stream.next(m.origin_x);
      stream.next(m.origin_y);
      stream.next(m.PlaneGridMap);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaneMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fitplane::PlaneMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fitplane::PlaneMap_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<int16_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<int16_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_x: ";
    Printer<float>::stream(s, indent + "  ", v.origin_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_y: ";
    Printer<float>::stream(s, indent + "  ", v.origin_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "PlaneGridMap: ";
    if (v.PlaneGridMap.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.PlaneGridMap.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::fitplane::Plane_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.PlaneGridMap[i]);
    }
    if (v.PlaneGridMap.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // FITPLANE_MESSAGE_PLANEMAP_H
