// Generated by gencpp from file fitplane/Plane.msg
// DO NOT EDIT!


#ifndef FITPLANE_MESSAGE_PLANE_H
#define FITPLANE_MESSAGE_PLANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fitplane
{
template <class ContainerAllocator>
struct Plane_
{
  typedef Plane_<ContainerAllocator> Type;

  Plane_()
    : PlaneCellHeight(0.0)
    , PlaneCellAngle(0.0)  {
    }
  Plane_(const ContainerAllocator& _alloc)
    : PlaneCellHeight(0.0)
    , PlaneCellAngle(0.0)  {
  (void)_alloc;
    }



   typedef float _PlaneCellHeight_type;
  _PlaneCellHeight_type PlaneCellHeight;

   typedef float _PlaneCellAngle_type;
  _PlaneCellAngle_type PlaneCellAngle;





  typedef boost::shared_ptr< ::fitplane::Plane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fitplane::Plane_<ContainerAllocator> const> ConstPtr;

}; // struct Plane_

typedef ::fitplane::Plane_<std::allocator<void> > Plane;

typedef boost::shared_ptr< ::fitplane::Plane > PlanePtr;
typedef boost::shared_ptr< ::fitplane::Plane const> PlaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fitplane::Plane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fitplane::Plane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fitplane::Plane_<ContainerAllocator1> & lhs, const ::fitplane::Plane_<ContainerAllocator2> & rhs)
{
  return lhs.PlaneCellHeight == rhs.PlaneCellHeight &&
    lhs.PlaneCellAngle == rhs.PlaneCellAngle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fitplane::Plane_<ContainerAllocator1> & lhs, const ::fitplane::Plane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fitplane

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fitplane::Plane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fitplane::Plane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane::Plane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane::Plane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane::Plane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane::Plane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fitplane::Plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92467c111abb460b6d16e58287e7864b";
  }

  static const char* value(const ::fitplane::Plane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92467c111abb460bULL;
  static const uint64_t static_value2 = 0x6d16e58287e7864bULL;
};

template<class ContainerAllocator>
struct DataType< ::fitplane::Plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fitplane/Plane";
  }

  static const char* value(const ::fitplane::Plane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fitplane::Plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 PlaneCellHeight\n"
"float32 PlaneCellAngle\n"
;
  }

  static const char* value(const ::fitplane::Plane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fitplane::Plane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PlaneCellHeight);
      stream.next(m.PlaneCellAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Plane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fitplane::Plane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fitplane::Plane_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "PlaneCellHeight: ";
    Printer<float>::stream(s, indent + "  ", v.PlaneCellHeight);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "PlaneCellAngle: ";
    Printer<float>::stream(s, indent + "  ", v.PlaneCellAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FITPLANE_MESSAGE_PLANE_H
