// Generated by gencpp from file fitplane_planner/GlobalPath.msg
// DO NOT EDIT!


#ifndef FITPLANE_PLANNER_MESSAGE_GLOBALPATH_H
#define FITPLANE_PLANNER_MESSAGE_GLOBALPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace fitplane_planner
{
template <class ContainerAllocator>
struct GlobalPath_
{
  typedef GlobalPath_<ContainerAllocator> Type;

  GlobalPath_()
    : header()
    , map_version(0)
    , poses()
    , corridor_half_width()
    , path_confidence()  {
    }
  GlobalPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , map_version(0)
    , poses(_alloc)
    , corridor_half_width(_alloc)
    , path_confidence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _map_version_type;
  _map_version_type map_version;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _corridor_half_width_type;
  _corridor_half_width_type corridor_half_width;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _path_confidence_type;
  _path_confidence_type path_confidence;





  typedef boost::shared_ptr< ::fitplane_planner::GlobalPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fitplane_planner::GlobalPath_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalPath_

typedef ::fitplane_planner::GlobalPath_<std::allocator<void> > GlobalPath;

typedef boost::shared_ptr< ::fitplane_planner::GlobalPath > GlobalPathPtr;
typedef boost::shared_ptr< ::fitplane_planner::GlobalPath const> GlobalPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fitplane_planner::GlobalPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fitplane_planner::GlobalPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fitplane_planner::GlobalPath_<ContainerAllocator1> & lhs, const ::fitplane_planner::GlobalPath_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.map_version == rhs.map_version &&
    lhs.poses == rhs.poses &&
    lhs.corridor_half_width == rhs.corridor_half_width &&
    lhs.path_confidence == rhs.path_confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fitplane_planner::GlobalPath_<ContainerAllocator1> & lhs, const ::fitplane_planner::GlobalPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fitplane_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fitplane_planner::GlobalPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fitplane_planner::GlobalPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fitplane_planner::GlobalPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9916ef7263e04949af022154c3512e69";
  }

  static const char* value(const ::fitplane_planner::GlobalPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9916ef7263e04949ULL;
  static const uint64_t static_value2 = 0xaf022154c3512e69ULL;
};

template<class ContainerAllocator>
struct DataType< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fitplane_planner/GlobalPath";
  }

  static const char* value(const ::fitplane_planner::GlobalPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Global reference path for UGV (UAV → UGV)\n"
"std_msgs/Header header\n"
"uint32 map_version                # 地图/路径版本（UAV 侧每次接收新图自增）\n"
"geometry_msgs/Pose[] poses        # 路径控制点（世界系）\n"
"float32[] corridor_half_width     # 对应poses的走廊半宽 w_i，单位m\n"
"float32[] path_confidence         # 对应poses的段置信度 c_i ∈ [0,1]\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::fitplane_planner::GlobalPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.map_version);
      stream.next(m.poses);
      stream.next(m.corridor_half_width);
      stream.next(m.path_confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlobalPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fitplane_planner::GlobalPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fitplane_planner::GlobalPath_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_version: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.map_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "poses: ";
    if (v.poses.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.poses[i]);
    }
    if (v.poses.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "corridor_half_width: ";
    if (v.corridor_half_width.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.corridor_half_width.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.corridor_half_width[i]);
    }
    if (v.corridor_half_width.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path_confidence: ";
    if (v.path_confidence.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.path_confidence.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.path_confidence[i]);
    }
    if (v.path_confidence.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // FITPLANE_PLANNER_MESSAGE_GLOBALPATH_H
